
# Definimos el puerto definitivo (8088 para que no choque con otros)
server.port=8088
server.address=0.0.0.0

# Identidad única del microservicio y perfil de desarrollo
spring.application.name=ms-bodegas
spring.profiles.active=dev


# Conexión directa a tu Oracle local sin Wallets ni nubes
# spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
# spring.datasource.username=SCHEMA_BODEGAS
# spring.datasource.password=FullStack-Bodega1
# spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


# Hibernate creará/actualizará las tablas automáticamente en Laragon
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Habilita la interfaz gráfica para probar tus endpoints en el navegador

spring.datasource.url=jdbc:mysql://localhost:3306/db_bodega
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html